config/routes.rb
Rails.application.routes.draw do
  resources :compromissos
  get 'nosotros/informacion'
  post'articles/new'
  get 'welcome/index'
  resources :nosotros
  resources :articles
  resources :fotografos

  
  

end

app/models/compromisso.rb
class Compromisso < ActiveRecord::Base
	
end

app/models/fotografo.rb
class Fotografo < ActiveRecord::Base
	 has_one :compromissos
	 has_attached_file :image
	 validates :image, :attachment_presence => true
	
	 validates_attachment :image, content_type: { content_type: ["image/jpg", "image/jpeg", "image/png", "image/gif"] }
	 # Validate filename
	 validates_attachment_file_name :image, :matches => [/png\Z/, /jpe?g\Z/, /gif\Z/]
	 # Explicitly do not validate
	 do_not_validate_attachment_file_type :image
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  def show

  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
	## aqui es para decir que en edit , show, update , destroy se usa el comando @fotografos=Fotografo.find(params[:id])
	before_action :set_fotografo, only:[:edit, :update , :destroy]

	def index
		@fotografo=Fotografo.all
	end

    def edit
    end

    def create
		@fotografo=Fotografo.new(article_params)

  		@fotografo.save
  		redirect_to @fotografo
	end

	def show
		@fotografo=Fotografo.all
    end

	def new
		@fotografo=Fotografo.new
	end
 
    def destroy
    	@fotografo.destroy
 
  		redirect_to articles_path
    end
	

	private
	  def set_fotografo
	  	@fotografo=Fotografo.find(params[:id])
	  end

	  def article_params
	  	## aqui se define los atributos que seran utilizados por seguridad
	    params.require(:fotografo).permit(:image,:nombrePila,:apellido,:telefono,:fechaNacimiento,:rut,:email,:comentarios)
	  end

	
	
end

app/controllers/compromissos_controller.rb
class CompromissosController < ApplicationController
  before_action :set_compromisso, only: [:show, :edit, :update, :destroy]

  # GET /compromissos
  # GET /compromissos.json
  def index
    @compromissos = Compromisso.all
    @date = params[:month] ? Date.parse(params[:month]) : Date.today
  end

  # GET /compromissos/1
  # GET /compromissos/1.json
  def show
  end

  # GET /compromissos/new
  def new
    @compromisso = Compromisso.new
  end

  # GET /compromissos/1/edit
  def edit
  end

  # POST /compromissos
  # POST /compromissos.json
  def create
    @compromisso = Compromisso.new(compromisso_params)

    respond_to do |format|
      if @compromisso.save
        format.html { redirect_to @compromisso, notice: 'Compromisso was successfully created.' }
        format.json { render :show, status: :created, location: @compromisso }
      else
        format.html { render :new }
        format.json { render json: @compromisso.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /compromissos/1
  # PATCH/PUT /compromissos/1.json
  def update
    respond_to do |format|
      if @compromisso.update(compromisso_params)
        format.html { redirect_to @compromisso, notice: 'Compromisso was successfully updated.' }
        format.json { render :show, status: :ok, location: @compromisso }
      else
        format.html { render :edit }
        format.json { render json: @compromisso.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /compromissos/1
  # DELETE /compromissos/1.json
  def destroy
    @compromisso.destroy
    respond_to do |format|
      format.html { redirect_to compromissos_url, notice: 'Compromisso was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_compromisso
      @compromisso = Compromisso.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def compromisso_params
      params.require(:compromisso).permit(:titulo, :texto, :date)
    end
end

app/controllers/fotografos_controller.rb
class FotografosController < ApplicationController
	before_action :set_fotografo, only:[:show,:edit, :update , :destroy]

	def index
    	@fotografo=Fotografo.all
  	end

	def edit
    end

    def update
	    @fotografo = Fotografo.find(params[:id])
	 
	    if @fotografo.update(article_params)
	      redirect_to @fotografo
	    else
	      render 'edit'
	    end
	end

    def destroy
    	@fotografo.destroy
 
  		redirect_to fotografos_path
    end
    
    def edit
    end
	
	def new
		@fotografo=Fotografo.new
	end

	def create
		@fotografo=Fotografo.new(article_params)

  		@fotografo.save
  		redirect_to @fotografo
	end

	def show
	end

	private
	  def set_fotografo
	  	@fotografo=Fotografo.find(params[:id])
	  end

	  def article_params
	  	## aqui se define los atributos que seran utilizados por seguridad
	    params.require(:fotografo).permit(:image,:nombrePila,:apellido,:telefono,:fechaNacimiento,:rut,:email,:comentarios)
	  	
	  
	  end

end

app/controllers/nosotros_controller.rb
class NosotrosController < ApplicationController
  
  def show
  		@fotografo= Fotografo.all
  end

  def informacion
    	@fotografo = Fotografo.page(params[:page]).per(3)
  	end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/compromissos_helper.rb
module CompromissosHelper
end

app/helpers/fotografos_helper.rb
module FotografosHelper
end

app/helpers/nosotros_helper.rb
module NosotrosHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/articles/destroy.html.erb
destroy.html.erb

app/views/articles/new.html.erb
<%= form_for @fotografo , html: { multipart: true } do |f| %>
    
  <p id="pe">
    <%= f.label :image %><br>
    <%= f.file_field :image %>
  </p>
  <p id="pe">
    <%= f.label :nombrePila %><br>
    <%= f.text_field :nombrePila %>
  </p>
  <p id="pe">
    <%= f.label :apellido %><br>
    <%= f.text_field :apellido %>
  </p>
  <p id="pe">
    <%= f.label :telefono %><br>
    <%= f.text_field :telefono %>
  </p>
  <p id="pe">
    <%= f.label :fechaNacimiento %><br>
    <%= f.text_field :fechaNacimiento %>
  </p>
  <p id="pe">
    <%= f.label :rut %><br>
    <%= f.text_field :rut %>
  </p>
  <p id="pe">
    <%= f.label :email %><br>
    <%= f.text_field  :email %>
  </p>
 
  <p id="pe">
    <%= f.label :comentarios %><br>
    <%= f.text_area  :comentarios %>
  </p>
 
  <p id="pe">
    <%= f.submit %>
   

  </p>


<% end %>




  

app/views/compromissos/_form.html.erb
<%= form_for(@compromisso) do |f| %>
  <% if @compromisso.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@compromisso.errors.count, "error") %> prohibited this compromisso from being saved:</h2>

      <ul>
      <% @compromisso.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :titulo %><br>
    <%= f.text_field :titulo %>
  </div>
  <div class="field">
    <%= f.label :texto %><br>
    <%= f.text_area :texto %>
  </div>
  <div class="field">
    <%= f.label :date %><br>
    <%= f.date_select :date %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/compromissos/edit.html.erb
<h1>Editing Compromisso</h1>

<%= render 'form' %>

<%= link_to 'Show', @compromisso %> |
<%= link_to 'Back', compromissos_path %>

app/views/compromissos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Compromissos</h1>

<table>
  <thead>
    <tr>
      <th>Titulo</th>
      <th>Texto</th>
      <th>Date</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @compromissos.each do |compromisso| %>
      <tr>
        <td><%= compromisso.titulo %></td>
        <td><%= compromisso.texto %></td>
        <td><%= compromisso.date %></td>
        <td><%= link_to 'Show', compromisso %></td>
        <td><%= link_to 'Edit', edit_compromisso_path(compromisso) %></td>
        <td><%= link_to 'Destroy', compromisso, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'nuevo compromiso', new_compromisso_path %>

<div id="calendar">
  <h2 id="month">
    <%= link_to "<", :month => (@date.beginning_of_month-1).strftime("%Y-%m-%d") %>
    <%=h @date.strftime("%B %Y") %>
    <%= link_to ">", :month => (@date.end_of_month+1).strftime("%Y-%m-%d") %>
  </h2>
  <%= calendar_for @compromissos, :year => @date.year, :month => @date.month do |t| %>
  <%= t.head('DOMINGO','LUNES', 'MARTES', 'MIERCOLES', 'JUEVES', 'VIERNES', 'SABADO') %>
  <%= t.day do |day, compromissos| %>
  <%= day.day %>
  <% compromissos.each do |compromisso| %><br>
  <%= link_to h(compromisso.titulo), compromisso %><br>
  <%= link_to 'Editar', edit_compromisso_path(compromisso) %> | <%= link_to 'Deletar', compromisso, method: :delete, data: { confirm: 'Esta seguro?' } %>
  <% end %>
  <% end %>
  <% end %>
</div>
<%= link_to 'Nuevo comprosimo', new_compromisso_path %>

app/views/compromissos/new.html.erb
<h1>New Compromisso</h1>

<%= render 'form' %>

<%= link_to 'Back', compromissos_path %>

app/views/compromissos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Titulo:</strong>
  <%= @compromisso.titulo %>
</p>

<p>
  <strong>Texto:</strong>
  <%= @compromisso.texto %>
</p>

<p>
  <strong>Date:</strong>
  <%= @compromisso.date %>
</p>

<%= link_to 'Edit', edit_compromisso_path(@compromisso) %> |
<%= link_to 'Back', compromissos_path %>

app/views/fotografos/edit.html.erb
<h1>Editando fotografo</h1>
 
<%= form_for :fotografo, html: { multipart: true } ,url: fotografo_path(@fotografo), method: :patch do |f| %>
  <% if @fotografo.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@fotografo.errors.count, "error") %> prohibited
      this article from being saved:</h2>
    <ul>
    <% @fotografo.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
  <% end %>
  
 <p id="pe">
    <%= f.label :image %><br>
    <%= f.file_field :image %>
  </p>
  <p id="pe">
    <%= f.label :nombrePila %><br>
    <%= f.text_field :nombrePila %>
  </p>
  <p id="pe">
    <%= f.label :apellido %><br>
    <%= f.text_field :apellido %>
  </p>
  <p id="pe">
    <%= f.label :telefono %><br>
    <%= f.text_field :telefono %>
  </p>
  <p id="pe">
    <%= f.label :fechaNacimiento %><br>
    <%= f.text_field :fechaNacimiento %>
  </p>
  <p id="pe">
    <%= f.label :rut %><br>
    <%= f.text_field :rut %>
  </p>
  <p id="pe">
    <%= f.label :email %><br>
    <%= f.text_field  :email %>
  </p>
 
  <p id="pe">
    <%= f.label :comentarios %><br>
    <%= f.text_area  :comentarios %>
  </p>




      
      
  
      
     
 
  <p>
    <%= f.submit %>
  </p>
<% end %>
<!--fotografo_path nos redirige al show del @fotografo-->
<!--fotografos_path nos redirige a los fotografos tabla-->
<%= link_to 'atras', fotografo_path %>

app/views/fotografos/index.html.erb
<% @fotografo.each do |f| %>
  <tr>
    <td><%= f.nombrePila %></td>
    <td><%= f.fechaNacimiento %></td>
    <td><%= link_to 'Show', fotografo_path(f) %></td>
    <td><%= link_to 'Edit', edit_fotografo_path(f) %></td>
    <td><%= link_to 'Destroy', fotografo_path(f),
                    method: :delete, data: { confirm: 'Esta seguro?' } %></td>
    </br>
  </tr>
<% end %>
</table>

app/views/fotografos/show.html.erb
<div class="my-skills text-center">
	<div class="container">
		<h3 >Profesional</h3>
		<div class="strip text-center"><%= image_tag("icons/tuerca.png")%> </div>


		<div class="skill-grids">
					<div class="col-md-1 skills-grid alaizq">
						<div class="circle" id="circles-1"></div>
						<p id="pe">Photoshop</p>
					</div>
					<div class="col-md-2 skills-grid alaizq">
						<div class="circle" id="circles-2"></div>
						<p id="pe">Illustrator</p>
					</div>
					

					<div class="clearfix"> </div>
				 <%= javascript_include_tag 'circles', :type => 'text/javascript' %>
				 <!--<script type="text/javascript" src="assets/javascripts/circles.js"></script>-->
					         <script>
								var colors = [
										['#6ed4c0', '#ffffff'], ['#6ed4c0', '#ffffff'], ['#6ed4c0', '#ffffff'], ['#6ed4c0', '#ffffff'], ['#6ed4c0', '#ffffff'], ['#6ed4c0', '#ffffff']
									];
								for (var i = 1; i <= 7; i++) {
									var child = document.getElementById('circles-' + i),
										percentage = 20 + (i * 20);
										
									Circles.create({
										id:         child.id,
										percentage: percentage,
										radius:     80,
										width:      10,
										number:   	percentage / 1,
										text:       '%',
										colors:     colors[i - 1]
									});
								}
							
							</script>
							
		</div>
	</div>	
</div>








</br>
</br>
</br>
</br>
</br>
</br>
</br>
</br>
</br>
</br>
</br>
</br>
</br>
</br>
</br>

</br>
</br>
</br>
</br>
</br>
<%= image_tag(@fotografo.image.url, size: "80x160" )%>
</br>

<%= @fotografo.nombrePila %>
</br>
<%= @fotografo.fechaNacimiento %>
</br>
<%= select_tag "favorite_color", '<option value="red">Red</option><option value="green">Green</option><option value="blue">Blue</option>'.html_safe %> 
</br>
<%= link_to 'Fotografos', fotografos_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>

  <title>Paginafotografica</title>
  <link href='https://fonts.googleapis.com/css?family=Great+Vibes' rel='stylesheet' type='text/css'>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>

  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>


	<nav>
	<section class="menu">

	    <div class="menu-content">
	    
	    <div class="logo" style="font-family: 'Great Vibes', cursive; font-size:240%">Lapsus Foto</div>
	    
	      <ul id="menu">
	        <li><a href="/welcome/index">INICIO</a></li>
	        <li><a href="#portafolio">PORTAFOLIO</a></li>
	        <li><a href="/nosotros/informacion">NOSOTRO</a></li>
	        <li><a href="#contact">CONTACTO</a></li>
	      </ul>
	    </div>
	  
	  
	  </section>
	</nav>






    
<%= yield %>

</body>

<footer>
<section class="partners parallax-background-partners" id="partners">
    
    <div class="opacity"></div>
    
      <div class="content">
      
        <h2>VIVE SIN REMORDIMIENTO</h2>
        
            <div class="logo">
          
                  
		        <div class="logo"><%= image_tag("logo-footer.png")%></div>
		        <div class="menu-footer">
		        
		          <a id="a1" href="#home">Home</a>
		          <a id="a2" href="#">Privacy policy</a>
		          <a id="a3" href="#">RSS</a>
		          <a id="a4" href="#">Facebook</a>
		          <a id="a5" href="#">Dribble</a>
		          <a id="a6" href="#">Twitter</a>
		          <a id="a7" href="#">Contact</a>
		        
		        </div>
		        
		        <div class="copyright">© 2016. All Rights Reserved zEEk</div>    
		    </div>
      
      </div>

    </section>
</footer>
</html>

app/views/nosotros/informacion.html.erb
  <section class="about-us" id="about-us" >
  
  <div class="content" >
  
    <h1>Lapsus Photos</h1>
    <hr/>
    <p class="title">Lapsus es una empresa dedicada a la captura de los momentos</p>
      <section class="portfolio" id="portfolio">


      <div class="portfolio-margin">
      
        <h2>FOTOGRAFOS PROFESIONALES</h2>


            <% @fotografo.each do |f| %>
            <center><div class="column-one" >
        
              

                <!--muestra imagen 
                <div>

                  <%= image_tag(f.image.url, size: "80x160" )%>
                </div>
                -->
                
                
                <h2><%= f.nombrePila %>  <%= f.apellido %></h2> 
                
                <p>Telefono : <%= f.telefono %></p><tab></tab>
                <p>Mail : <%= f.email %></p>
                
                <%= link_to fotografo_path(f) do %>
                <div class="circle-one" ></div>
                <%end%>

                 
            </div>
            </center>
            <%end%>
            <center><%= paginate @fotografo %>
            <%= page_entries_info @fotografo %>
            </center>
            </br>
      </div>   
         
      </section>
      <p></p>
  </div>
 
  </section>

  

app/views/welcome/index.html.erb
<!-- section start-page -->
<section class="start-page parallax-background" id="home">
  
    <div class="opacity"></div> <!-- Opacity color -->
      <div class="content">
        <div class="text">
        
          <div class="logo"><%= image_tag("logo.png") %></div>
        
          <h1>lo eterno en un segundo</h1><hr/>
          <p>Familiarizase con nosotros</p>
          
          <a href="#about-us"><div class="read-more">Ver mas</div></a>
          
        </div>
        <div class="arrow-down"></div>
      </div>
  
  </section>

  <!-- portoflio-->

  <section class="portfolio" id="portfolio">


    <div class="portfolio-margin">
    
      <h1>UN SEGUNDO DE TU VIDA</h1>
      <hr/> 
    
    <!-- 1 item portoflio-->
    
        <ul class="grid">
        
          <li>
            <a href="#">
              <%= image_tag("portfolio/1.png", :alt => "Portfolio item") %>
                <div class="text">
                  <p>PORTFOLIO 1</p>
                  <p class="description">Your text here...</p>   
              </div>
            </a>
          </li>
          
          <!-- 2 item portoflio-->
          
          <li>
            <a href="#">
              <%= image_tag("portfolio/2.png", :alt => "Portfolio item") %>
                <div class="no-text">
                  <p></p>
                  <p class="description"></p>               
              </div>
            </a>
          </li>      

          <!-- 3 item portoflio-->
          
          <li>
            <a href="#">
              	<%= image_tag("portfolio/3.png", :alt => "Portfolio item") %>
                <div class="no-text">
                  <p></p> 
                  <p class="description"></p>           
              </div>
            </a>
          </li>      


          <!-- 4 item portoflio-->
          
          <li>
            <a href="#">
              <%= image_tag("portfolio/4.png", :alt => "Portfolio item") %>
                <div class="no-text">
                  <p></p> 
                  <p class="description"></p>         
              </div>
            </a>
          </li>    

          <!-- 5 item portoflio-->
          
          <li>
            <a href="#">
              <%= image_tag("portfolio/5.png", :alt => "Portfolio item") %>
                <div class="no-text">
                  <p></p> 
                  <p class="description"></p>            
              </div>
            </a>
          </li>    
          

          <!-- 6 item portoflio-->
          
          <li>
            <a href="#">
              <%= image_tag("portfolio/6.png", :alt => "Portfolio item") %>
                <div class="text">
                  <p>PORTFOLIO 6</p> 
                  <p class="description">Your text here...</p>           
              </div>
            </a>
          </li>         
           
         <!-- 7 item portoflio-->
          
          <li>
            <a href="#">
              <%= image_tag("portfolio/7.png", :alt => "Portfolio item") %>
                <div class="text">
                  <p>PORTFOLIO 7</p> 
                  <p class="description">Your text here...</p>           
              </div>
            </a>
          </li>    
          
          <!-- 8 item portoflio-->
          
          <li>
            <a href="#">
              <%= image_tag("portfolio/8.png", :alt => "Portfolio item") %>
                <div class="text">
                  <p>PORTFOLIO 8</p> 
                  <p class="description">Your text here...</p>           
              </div>
            </a>
          </li>          
          
          <!-- 9 item portoflio-->
          
          <li>
            <a href="#">
            	<%= image_tag("portfolio/9.png", :alt => "Portfolio item") %>
                <div class="text">
                  <p>PORTFOLIO 9</p> 
                  <p class="description">Your text here...</p>           
              </div>
            </a>
          </li>          

          <!-- 10 item portoflio-->
          
          <li>
            <a href="#">
              <%= image_tag("portfolio/10.png", :alt => "Portfolio item") %>
                <div class="text">
                  <p>PORTFOLIO 11</p> 
                  <p class="description">Your text here...</p>           
              </div>
            </a>
          </li>         

          <!-- 11 item portoflio-->
          
          <li>
            <a href="#">
              <%= image_tag("portfolio/11.png", :alt => "Portfolio item") %>
                <div class="text">
                  <p>PORTFOLIO 11</p> 
                  <p class="description">Your text here...</p>           
              </div>
            </a>
          </li>          
 
 
          
        </ul>  
   
   <a href="#"><div class="read-more">VER MAS</div></a>
   
   </div>   
         
   </section>

  
   <div class="clear"></div>

   